### ISSUE TITLE
TMC Drivers

### ISSUE THREAD

**Issue by pacocatech** [NARUTOfzr/Elegoo-Neptune-marlin2.1.1#6]
it is not necessary to set the TMC drivers in the configuration?

**Comment by sroemer** [comment]
As far as I remember the board does not use real TMC stepper drivers. Now I didn't find the used chips, but those are compatible to the ones configured in Configuration.h (A4988). As far as I can tell everything is working fine and I trust Elegoo/Narutofzr in that point.

Additionally basic questions like this should not be discussed in an issue of a specific Elegoo firmware repository. If you need help with Configuration of Marlin, then better find some general Marlin related forum, search on reddit or similar...

**Comment by NARUTOfzr** [comment]
@pacocatech The motherboard uses MS35774/5 (which is a replacement for the TMC2208). Because the axle drive does not use Uart mode, it does not need to be set to TMC specifically.

**Comment by pacocatech** [comment]
@NARUTOfzr thank you very much!
